In [3]:
import numpy as np

##### The basics

In [15]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [5]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
# Get Dimension
b.ndim

2

In [10]:
# Get Shape
b.shape

(2, 3)

In [20]:
# Get Type 
a.dtype

dtype('int32')

In [23]:
# Get Size
a.itemsize

4

In [19]:
# Get total size
a.nbytes

12

#### Accessing/Changing specific elements, rows, columns, etc

In [25]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [34]:
# Get a specific element [r,c]
a[1, 5]

np.int64(13)

In [42]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [41]:
# Get a specific column
a[:,0]

array([1, 8])

In [48]:
# Getting a little more fancy [startindex : endindex : stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [55]:
a[1,5] = 20

a[:,2] = [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

*3-d example

In [60]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [64]:
# Get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [66]:
# replace
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])