In [3]:
import numpy as np

##### The basics

In [15]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [5]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
# Get Dimension
b.ndim

2

In [10]:
# Get Shape
b.shape

(2, 3)

In [20]:
# Get Type 
a.dtype

dtype('int32')

In [23]:
# Get Size
a.itemsize

4

In [19]:
# Get total size
a.nbytes

12

#### Accessing/Changing specific elements, rows, columns, etc

In [25]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [34]:
# Get a specific element [r,c]
a[1, 5]

np.int64(13)

In [42]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [41]:
# Get a specific column
a[:,0]

array([1, 8])

In [48]:
# Getting a little more fancy [startindex : endindex : stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [55]:
a[1,5] = 20

a[:,2] = [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

*3-d example

In [60]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [64]:
# Get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [66]:
# replace
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

Initializing Different Types of Arrays

In [69]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [73]:
# All 1s matrix
np.ones((4,2,2),dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [77]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [79]:
# Any othrer number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [83]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.30045499, 0.01294252],
       [0.73336799, 0.79229789],
       [0.08032978, 0.7583581 ],
       [0.7201759 , 0.53388532]])

In [90]:
# Random Integer values
np.random.randint(-4,7,size=(3,3))

array([[ 5,  3, -1],
       [ 0,  1,  0],
       [ 1, -1,  6]], dtype=int32)

In [91]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])